In [53]:
import pandas as pd
df = pd.read_csv('fraudTrain.csv')

In [54]:
df

Unnamed: 0 trans_date_trans_time               cc_num  \
0                 0   2019-01-01 00:00:18     2703186189652095   
1                 1   2019-01-01 00:00:44         630423337322   
2                 2   2019-01-01 00:00:51       38859492057661   
3                 3   2019-01-01 00:01:16     3534093764340240   
4                 4   2019-01-01 00:03:06      375534208663984   
...             ...                   ...                  ...   
1296670     1296670   2020-06-21 12:12:08       30263540414123   
1296671     1296671   2020-06-21 12:12:19     6011149206456997   
1296672     1296672   2020-06-21 12:12:32     3514865930894695   
1296673     1296673   2020-06-21 12:13:36     2720012583106919   
1296674     1296674   2020-06-21 12:13:37  4292902571056973207   

                                    merchant       category     amt  \
0                 fraud_Rippin, Kub and Mann       misc_net    4.97   
1            fraud_Heller, Gutmann and Zieme    grocery_pos  107.23   
2                       fraud_Lind-Buckridge  entertainment  220.11   
3         fraud_Kutch, Hermiston and Farrell  gas_transport   45.00   
4                        fraud_Keeling-Crist       misc_pos   41.96   
...                                      ...            ...     ...   
1296670                    fraud_Reichel Inc  entertainment   15.56   
1296671             fraud_Abernathy and Sons    food_dining   51.70   
1296672                 fraud_Stiedemann Ltd    food_dining  105.93   
1296673  fraud_Reinger, Weissnat and Strosin    food_dining   74.90   
1296674  fraud_Langosh, Wintheiser and Hyatt    food_dining    4.30   

               first       last gender                         street  ...  \
0           Jennifer      Banks      F                 561 Perry Cove  ...   
1          Stephanie       Gill      F   43039 Riley Greens Suite 393  ...   
2             Edward    Sanchez      M       594 White Dale Suite 530  ...   
3             Jeremy      White      M    9443 Cynthia Court Apt. 038  ...   
4              Tyler     Garcia      M               408 Bradley Rest  ...   
...              ...        ...    ...                            ...  ...   
1296670         Erik  Patterson      M       162 Jessica Row Apt. 072  ...   
1296671      Jeffrey      White      M  8617 Holmes Terrace Suite 651  ...   
1296672  Christopher  Castaneda      M     1632 Cohen Drive Suite 639  ...   
1296673       Joseph     Murray      M           42933 Ryan Underpass  ...   
1296674      Jeffrey      Smith      M           135 Joseph Mountains  ...   

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling   
1        48.8878 -118.2105       149  Special educational needs teacher   
2        42.1808 -112.2620      4154        Nature conservation officer   
3        46.2306 -112.1138      1939                    Patent attorney   
4        38.4207  -79.4629        99     Dance movement psychotherapist   
...          ...       ...       ...                                ...   
1296670  37.7175 -112.4777       258                       Geoscientist   
1296671  39.2667  -77.5101       100   Production assistant, television   
1296672  32.9396 -105.8189       899                    Naval architect   
1296673  43.3526 -102.5411      1126              Volunteer coordinator   
1296674  45.8433 -113.8748       218           Therapist, horticultural   

                dob                         trans_num   unix_time  merch_lat  \
0        1988-03-09  0b242abb623afc578575680df30655b9  1325376018  36.011293   
1        1978-06-21  1f76529f8574734946361c461b024d99  1325376044  49.159047   
2        1962-01-19  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704   
3        1967-01-12  6b849c168bdad6f867558c3793159a81  1325376076  47.034331   
4        1986-03-28  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999   
...             ...                          

In [55]:
from sklearn.preprocessing import OneHotEncoder

In [56]:
print(x)

[[ 0.00000000e+00  8.00000000e+00  4.97000000e+00 ... -8.20483150e+01
   0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  4.00000000e+00  1.07230000e+02 ... -1.18186462e+02
   0.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00  0.00000000e+00  2.20110000e+02 ... -1.12154481e+02
   0.00000000e+00  0.00000000e+00]
 ...
 [ 1.29667200e+06  1.00000000e+00  1.05930000e+02 ... -1.05130529e+02
   0.00000000e+00  0.00000000e+00]
 [ 1.29667300e+06  1.00000000e+00  7.49000000e+01 ... -1.03241160e+02
   0.00000000e+00  0.00000000e+00]
 [ 1.29667400e+06  1.00000000e+00  4.30000000e+00 ... -1.14186110e+02
   0.00000000e+00  0.00000000e+00]]


In [57]:
print(y)

[0 0 0 ... 0 0 0]


In [58]:
print(x)

[[ 0.00000000e+00  8.00000000e+00  4.97000000e+00 ... -8.20483150e+01
   0.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  4.00000000e+00  1.07230000e+02 ... -1.18186462e+02
   0.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00  0.00000000e+00  2.20110000e+02 ... -1.12154481e+02
   0.00000000e+00  0.00000000e+00]
 ...
 [ 1.29667200e+06  1.00000000e+00  1.05930000e+02 ... -1.05130529e+02
   0.00000000e+00  0.00000000e+00]
 [ 1.29667300e+06  1.00000000e+00  7.49000000e+01 ... -1.03241160e+02
   0.00000000e+00  0.00000000e+00]
 [ 1.29667400e+06  1.00000000e+00  4.30000000e+00 ... -1.14186110e+02
   0.00000000e+00  0.00000000e+00]]


In [59]:
x_drop = df.drop(['merchant','first','last','street','city','state','job','trans_date_trans_time','cc_num','trans_num','dob'], axis= 'columns')
x_drop.head()

Unnamed: 0       category     amt gender    zip      lat      long  \
0           0       misc_net    4.97      F  28654  36.0788  -81.1781   
1           1    grocery_pos  107.23      F  99160  48.8878 -118.2105   
2           2  entertainment  220.11      M  83252  42.1808 -112.2620   
3           3  gas_transport   45.00      M  59632  46.2306 -112.1138   
4           4       misc_pos   41.96      M  24433  38.4207  -79.4629   

   city_pop   unix_time  merch_lat  merch_long  is_fraud  
0      3495  1325376018  36.011293  -82.048315         0  
1       149  1325376044  49.159047 -118.186462         0  
2      4154  1325376051  43.150704 -112.154481         0  
3      1939  1325376076  47.034331 -112.561071         0  
4        99  1325376186  38.674999  -78.632459         0

In [60]:
print(x_drop)

         Unnamed: 0       category     amt gender    zip      lat      long  \
0                 0       misc_net    4.97      F  28654  36.0788  -81.1781   
1                 1    grocery_pos  107.23      F  99160  48.8878 -118.2105   
2                 2  entertainment  220.11      M  83252  42.1808 -112.2620   
3                 3  gas_transport   45.00      M  59632  46.2306 -112.1138   
4                 4       misc_pos   41.96      M  24433  38.4207  -79.4629   
...             ...            ...     ...    ...    ...      ...       ...   
1296670     1296670  entertainment   15.56      M  84735  37.7175 -112.4777   
1296671     1296671    food_dining   51.70      M  21790  39.2667  -77.5101   
1296672     1296672    food_dining  105.93      M  88325  32.9396 -105.8189   
1296673     1296673    food_dining   74.90      M  57756  43.3526 -102.5411   
1296674     1296674    food_dining    4.30      M  59871  45.8433 -113.8748   

         city_pop   unix_time  merch_lat  merch_lon

In [61]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
le = LabelEncoder()

# Assume we want to encode the column at position 2 (third column)
# It's better to refer to the column by name if possible
column_to_encode = x_drop.columns[1]

# Apply LabelEncoder to the specified column
x_drop[column_to_encode] = le.fit_transform(x_drop[column_to_encode])

# Print the first few rows of the dataframe to check
print(x_drop.head())


   Unnamed: 0  category     amt gender    zip      lat      long  city_pop  \
0           0         8    4.97      F  28654  36.0788  -81.1781      3495   
1           1         4  107.23      F  99160  48.8878 -118.2105       149   
2           2         0  220.11      M  83252  42.1808 -112.2620      4154   
3           3         2   45.00      M  59632  46.2306 -112.1138      1939   
4           4         9   41.96      M  24433  38.4207  -79.4629        99   

    unix_time  merch_lat  merch_long  is_fraud  
0  1325376018  36.011293  -82.048315         0  
1  1325376044  49.159047 -118.186462         0  
2  1325376051  43.150704 -112.154481         0  
3  1325376076  47.034331 -112.561071         0  
4  1325376186  38.674999  -78.632459         0  


In [62]:
print(x_drop)

         Unnamed: 0  category     amt gender    zip      lat      long  \
0                 0         8    4.97      F  28654  36.0788  -81.1781   
1                 1         4  107.23      F  99160  48.8878 -118.2105   
2                 2         0  220.11      M  83252  42.1808 -112.2620   
3                 3         2   45.00      M  59632  46.2306 -112.1138   
4                 4         9   41.96      M  24433  38.4207  -79.4629   
...             ...       ...     ...    ...    ...      ...       ...   
1296670     1296670         0   15.56      M  84735  37.7175 -112.4777   
1296671     1296671         1   51.70      M  21790  39.2667  -77.5101   
1296672     1296672         1  105.93      M  88325  32.9396 -105.8189   
1296673     1296673         1   74.90      M  57756  43.3526 -102.5411   
1296674     1296674         1    4.30      M  59871  45.8433 -113.8748   

         city_pop   unix_time  merch_lat  merch_long  is_fraud  
0            3495  1325376018  36.011293  -82.

In [63]:
pd.DataFrame(x_drop)

Unnamed: 0  category     amt gender    zip      lat      long  \
0                 0         8    4.97      F  28654  36.0788  -81.1781   
1                 1         4  107.23      F  99160  48.8878 -118.2105   
2                 2         0  220.11      M  83252  42.1808 -112.2620   
3                 3         2   45.00      M  59632  46.2306 -112.1138   
4                 4         9   41.96      M  24433  38.4207  -79.4629   
...             ...       ...     ...    ...    ...      ...       ...   
1296670     1296670         0   15.56      M  84735  37.7175 -112.4777   
1296671     1296671         1   51.70      M  21790  39.2667  -77.5101   
1296672     1296672         1  105.93      M  88325  32.9396 -105.8189   
1296673     1296673         1   74.90      M  57756  43.3526 -102.5411   
1296674     1296674         1    4.30      M  59871  45.8433 -113.8748   

         city_pop   unix_time  merch_lat  merch_long  is_fraud  
0            3495  1325376018  36.011293  -82.048315         0  
1             149  1325376044  49.159047 -118.186462         0  
2            4154  1325376051  43.150704 -112.154481         0  
3            1939  1325376076  47.034331 -112.561071         0  
4              99  1325376186  38.674999  -78.632459         0  
...           ...         ...        ...         ...       ...  
1296670       258  1371816728  36.841266 -111.690765         0  
1296671       100  1371816739  38.906881  -78.246528         0  
1296672       899  1371816752  33.619513 -105.130529         0  
1296673      1126  1371816816  42.788940 -103.241160         0  
1296674       218  1371816817  46.565983 -114.186110         0  

[1296675 rows x 12 columns]

In [64]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[2])],remainder='passthrough')

In [65]:
st = np.array(ct.fit_transform(st))

NameError: name 'np' is not defined

In [66]:
df_dummies = pd.get_dummies(x_drop, columns=['gender'])

boolean_columns = df_dummies.select_dtypes(include=['bool']).columns
df_dummies[boolean_columns] = df_dummies[boolean_columns].astype(int)

print(df_dummies)


         Unnamed: 0  category     amt    zip      lat      long  city_pop  \
0                 0         8    4.97  28654  36.0788  -81.1781      3495   
1                 1         4  107.23  99160  48.8878 -118.2105       149   
2                 2         0  220.11  83252  42.1808 -112.2620      4154   
3                 3         2   45.00  59632  46.2306 -112.1138      1939   
4                 4         9   41.96  24433  38.4207  -79.4629        99   
...             ...       ...     ...    ...      ...       ...       ...   
1296670     1296670         0   15.56  84735  37.7175 -112.4777       258   
1296671     1296671         1   51.70  21790  39.2667  -77.5101       100   
1296672     1296672         1  105.93  88325  32.9396 -105.8189       899   
1296673     1296673         1   74.90  57756  43.3526 -102.5411      1126   
1296674     1296674         1    4.30  59871  45.8433 -113.8748       218   

          unix_time  merch_lat  merch_long  is_fraud  gender_F  gender_M  


In [67]:
# Check for NaN values column-wise
nan_columns = df.isnull().any()

print("Columns with NaN values:")
print(nan_columns)


Columns with NaN values:
Unnamed: 0               False
trans_date_trans_time    False
cc_num                   False
merchant                 False
category                 False
amt                      False
first                    False
last                     False
gender                   False
street                   False
city                     False
state                    False
zip                      False
lat                      False
long                     False
city_pop                 False
job                      False
dob                      False
trans_num                False
unix_time                False
merch_lat                False
merch_long               False
is_fraud                 False
dtype: bool


In [68]:
x=df_dummies.iloc[:,:-1].values
y=df.iloc[:,-1].values
x

array([[ 0.00000000e+00,  8.00000000e+00,  4.97000000e+00, ...,
        -8.20483150e+01,  0.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  4.00000000e+00,  1.07230000e+02, ...,
        -1.18186462e+02,  0.00000000e+00,  1.00000000e+00],
       [ 2.00000000e+00,  0.00000000e+00,  2.20110000e+02, ...,
        -1.12154481e+02,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.29667200e+06,  1.00000000e+00,  1.05930000e+02, ...,
        -1.05130529e+02,  0.00000000e+00,  0.00000000e+00],
       [ 1.29667300e+06,  1.00000000e+00,  7.49000000e+01, ...,
        -1.03241160e+02,  0.00000000e+00,  0.00000000e+00],
       [ 1.29667400e+06,  1.00000000e+00,  4.30000000e+00, ...,
        -1.14186110e+02,  0.00000000e+00,  0.00000000e+00]])

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


In [71]:
x_train

array([[ 3.30201000e+05,  1.30000000e+01,  6.51000000e+00, ...,
        -9.14263770e+01,  0.00000000e+00,  1.00000000e+00],
       [ 7.98518000e+05,  0.00000000e+00,  2.01700000e+01, ...,
        -1.22739095e+02,  0.00000000e+00,  1.00000000e+00],
       [ 1.26037500e+06,  5.00000000e+00,  3.58500000e+01, ...,
        -9.53711190e+01,  0.00000000e+00,  1.00000000e+00],
       ...,
       [ 1.31932000e+05,  6.00000000e+00,  1.18270000e+02, ...,
        -1.06219762e+02,  0.00000000e+00,  1.00000000e+00],
       [ 6.71155000e+05,  1.20000000e+01,  5.60000000e+00, ...,
        -9.74987540e+01,  0.00000000e+00,  0.00000000e+00],
       [ 1.21958000e+05,  1.00000000e+01,  1.40730000e+02, ...,
        -8.28424430e+01,  0.00000000e+00,  1.00000000e+00]])

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
model = LogisticRegression()
l= pd.DataFrame(df_dummies)
l

Unnamed: 0  category     amt    zip      lat      long  city_pop  \
0                 0         8    4.97  28654  36.0788  -81.1781      3495   
1                 1         4  107.23  99160  48.8878 -118.2105       149   
2                 2         0  220.11  83252  42.1808 -112.2620      4154   
3                 3         2   45.00  59632  46.2306 -112.1138      1939   
4                 4         9   41.96  24433  38.4207  -79.4629        99   
...             ...       ...     ...    ...      ...       ...       ...   
1296670     1296670         0   15.56  84735  37.7175 -112.4777       258   
1296671     1296671         1   51.70  21790  39.2667  -77.5101       100   
1296672     1296672         1  105.93  88325  32.9396 -105.8189       899   
1296673     1296673         1   74.90  57756  43.3526 -102.5411      1126   
1296674     1296674         1    4.30  59871  45.8433 -113.8748       218   

          unix_time  merch_lat  merch_long  is_fraud  gender_F  gender_M  
0        1325376018  36.011293  -82.048315         0         1         0  
1        1325376044  49.159047 -118.186462         0         1         0  
2        1325376051  43.150704 -112.154481         0         0         1  
3        1325376076  47.034331 -112.561071         0         0         1  
4        1325376186  38.674999  -78.632459         0         0         1  
...             ...        ...         ...       ...       ...       ...  
1296670  1371816728  36.841266 -111.690765         0         0         1  
1296671  1371816739  38.906881  -78.246528         0         0         1  
1296672  1371816752  33.619513 -105.130529         0         0         1  
1296673  1371816816  42.788940 -103.241160         0         0         1  
1296674  1371816817  46.565983 -114.186110         0         0         1  

[1296675 rows x 13 columns]

In [74]:
model.fit(x_train,y_train)

LogisticRegression()

In [75]:
model.predict(x_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
model.score(x_test,y_test)

0.9941388551487458

In [77]:
from sklearn.neighbors import KNeighborsClassifier

In [78]:
knn = KNeighborsClassifier(n_neighbors = 100)

In [79]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=100)

In [80]:
knn.score(x_test,y_test)

0.9941388551487458

In [90]:
zk = pd.read_csv('fraudtest.csv')
zk

Unnamed: 0 trans_date_trans_time            cc_num  \
0                0   2020-06-21 12:14:25  2291163933867244   
1                1   2020-06-21 12:14:33  3573030041201292   
2                2   2020-06-21 12:14:53  3598215285024754   
3                3   2020-06-21 12:15:15  3591919803438423   
4                4   2020-06-21 12:15:17  3526826139003047   
...            ...                   ...               ...   
555714      555714   2020-12-31 23:59:07    30560609640617   
555715      555715   2020-12-31 23:59:09  3556613125071656   
555716      555716   2020-12-31 23:59:15  6011724471098086   
555717      555717   2020-12-31 23:59:24     4079773899158   
555718      555718   2020-12-31 23:59:34  4170689372027579   

                                    merchant        category     amt    first  \
0                      fraud_Kirlin and Sons   personal_care    2.86     Jeff   
1                       fraud_Sporer-Keebler   personal_care   29.84   Joanne   
2       fraud_Swaniawski, Nitzsche and Welch  health_fitness   41.28   Ashley   
3                          fraud_Haley Group        misc_pos   60.05    Brian   
4                      fraud_Johnston-Casper          travel    3.19   Nathan   
...                                      ...             ...     ...      ...   
555714                 fraud_Reilly and Sons  health_fitness   43.77  Michael   
555715                  fraud_Hoppe-Parisian       kids_pets  111.84     Jose   
555716                       fraud_Rau-Robel       kids_pets   86.88      Ann   
555717                 fraud_Breitenberg LLC          travel    7.99     Eric   
555718                     fraud_Dare-Marvin   entertainment   38.13   Samuel   

            last gender                       street  ...      lat      long  \
0        Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1       Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2          Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3       Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4         Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   
...          ...    ...                          ...  ...      ...       ...   
555714     Olson      M          558 Michael Estates  ...  40.4931  -91.8912   
555715   Vasquez      M          572 Davis Mountains  ...  29.0393  -95.4401   
555716    Lawson      F   144 Evans Islands Apt. 683  ...  46.1966 -118.9017   
555717   Preston      M   7020 Doyle Stream Apt. 951  ...  44.6255 -116.4493   
555718      Frey      M     830 Myers Plaza Apt. 384  ...  35.6665  -97.4798   

        city_pop                     job         dob  \
0         333497     Mechanical engineer  1968-03-19   
1            302  Sales professional, IT  1990-01-17   
2          34496       Librarian, public  1970-10-21   
3          54767            Set designer  1987-07-25   
4           1126      Furniture designer  1955-07-06   
...          ...                     ...         ...   
555714       519            Town planner  1966-02-13   
555715     28739          Futures trader  1999-12-27   
555716      3684                Musician  1981-11-29   
555717       129            Cartographer  1965-12-15   
555718    116001             Media buyer  1993-05-10   

                               trans_num   unix_time  merch_lat  merch_long  \
0       2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1       324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2       c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3       2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4       57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   
...                                  ...         ...        ...         ...   
555714  9b1f753c79894c9f4b71f04581835ada  1388534347  39.946837  -91.333331   
555715  2090647dac2c89a1

In [91]:
x_d = zk.drop(['merchant','first','last','street','city','state','job','trans_date_trans_time','cc_num','trans_num','dob'], axis= 'columns')
x_d.head()

Unnamed: 0        category    amt gender    zip      lat      long  \
0           0   personal_care   2.86      M  29209  33.9659  -80.9355   
1           1   personal_care  29.84      F  84002  40.3207 -110.4360   
2           2  health_fitness  41.28      F  11710  40.6729  -73.5365   
3           3        misc_pos  60.05      M  32780  28.5697  -80.8191   
4           4          travel   3.19      M  49632  44.2529  -85.0170   

   city_pop   unix_time  merch_lat  merch_long  is_fraud  
0    333497  1371816865  33.986391  -81.200714         0  
1       302  1371816873  39.450498 -109.960431         0  
2     34496  1371816893  40.495810  -74.196111         0  
3     54767  1371816915  28.812398  -80.883061         0  
4      1126  1371816917  44.959148  -85.884734         0

In [92]:
print(x_d)

        Unnamed: 0        category     amt gender    zip      lat      long  \
0                0   personal_care    2.86      M  29209  33.9659  -80.9355   
1                1   personal_care   29.84      F  84002  40.3207 -110.4360   
2                2  health_fitness   41.28      F  11710  40.6729  -73.5365   
3                3        misc_pos   60.05      M  32780  28.5697  -80.8191   
4                4          travel    3.19      M  49632  44.2529  -85.0170   
...            ...             ...     ...    ...    ...      ...       ...   
555714      555714  health_fitness   43.77      M  63453  40.4931  -91.8912   
555715      555715       kids_pets  111.84      M  77566  29.0393  -95.4401   
555716      555716       kids_pets   86.88      F  99323  46.1966 -118.9017   
555717      555717          travel    7.99      M  83643  44.6255 -116.4493   
555718      555718   entertainment   38.13      M  73034  35.6665  -97.4798   

        city_pop   unix_time  merch_lat  merch_long

In [93]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
xe = LabelEncoder()

# Assume we want to encode the column at position 2 (third column)
# It's better to refer to the column by name if possible
column_to_encode = x_d.columns[1]

# Apply LabelEncoder to the specified column
x_d[column_to_encode] = xe.fit_transform(x_d[column_to_encode])

# Print the first few rows of the dataframe to check
print(x_d.head())

   Unnamed: 0  category    amt gender    zip      lat      long  city_pop  \
0           0        10   2.86      M  29209  33.9659  -80.9355    333497   
1           1        10  29.84      F  84002  40.3207 -110.4360       302   
2           2         5  41.28      F  11710  40.6729  -73.5365     34496   
3           3         9  60.05      M  32780  28.5697  -80.8191     54767   
4           4        13   3.19      M  49632  44.2529  -85.0170      1126   

    unix_time  merch_lat  merch_long  is_fraud  
0  1371816865  33.986391  -81.200714         0  
1  1371816873  39.450498 -109.960431         0  
2  1371816893  40.495810  -74.196111         0  
3  1371816915  28.812398  -80.883061         0  
4  1371816917  44.959148  -85.884734         0  


In [84]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
zk = ColumnTransformer(transformers =[('encoder',OneHotEncoder(),[2])],remainder='passthrough')

In [94]:
df_dummi = pd.get_dummies(x_d, columns=['gender'])

boolean_columns = df_dummi.select_dtypes(include=['bool']).columns
df_dummi[boolean_columns] = df_dummi[boolean_columns].astype(int)

print(df_dummi)


        Unnamed: 0  category     amt    zip      lat      long  city_pop  \
0                0        10    2.86  29209  33.9659  -80.9355    333497   
1                1        10   29.84  84002  40.3207 -110.4360       302   
2                2         5   41.28  11710  40.6729  -73.5365     34496   
3                3         9   60.05  32780  28.5697  -80.8191     54767   
4                4        13    3.19  49632  44.2529  -85.0170      1126   
...            ...       ...     ...    ...      ...       ...       ...   
555714      555714         5   43.77  63453  40.4931  -91.8912       519   
555715      555715         7  111.84  77566  29.0393  -95.4401     28739   
555716      555716         7   86.88  99323  46.1966 -118.9017      3684   
555717      555717        13    7.99  83643  44.6255 -116.4493       129   
555718      555718         0   38.13  73034  35.6665  -97.4798    116001   

         unix_time  merch_lat  merch_long  is_fraud  gender_F  gender_M  
0       13718

In [99]:
m=df_dummi.iloc[:,:-1].values
n=zk.iloc[:,-1].values

print(m)

[[ 0.00000000e+00  1.00000000e+01  2.86000000e+00 ... -8.12007140e+01
   0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+01  2.98400000e+01 ... -1.09960431e+02
   0.00000000e+00  1.00000000e+00]
 [ 2.00000000e+00  5.00000000e+00  4.12800000e+01 ... -7.41961110e+01
   0.00000000e+00  1.00000000e+00]
 ...
 [ 5.55716000e+05  7.00000000e+00  8.68800000e+01 ... -1.19715054e+02
   0.00000000e+00  1.00000000e+00]
 [ 5.55717000e+05  1.30000000e+01  7.99000000e+00 ... -1.17080888e+02
   0.00000000e+00  0.00000000e+00]
 [ 5.55718000e+05  0.00000000e+00  3.81300000e+01 ... -9.70363720e+01
   0.00000000e+00  0.00000000e+00]]


In [100]:
n

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [101]:
from sklearn.linear_model import LogisticRegression

In [102]:
model = LogisticRegression()
l= pd.DataFrame(df_dummies)
l

Unnamed: 0  category     amt    zip      lat      long  city_pop  \
0                 0         8    4.97  28654  36.0788  -81.1781      3495   
1                 1         4  107.23  99160  48.8878 -118.2105       149   
2                 2         0  220.11  83252  42.1808 -112.2620      4154   
3                 3         2   45.00  59632  46.2306 -112.1138      1939   
4                 4         9   41.96  24433  38.4207  -79.4629        99   
...             ...       ...     ...    ...      ...       ...       ...   
1296670     1296670         0   15.56  84735  37.7175 -112.4777       258   
1296671     1296671         1   51.70  21790  39.2667  -77.5101       100   
1296672     1296672         1  105.93  88325  32.9396 -105.8189       899   
1296673     1296673         1   74.90  57756  43.3526 -102.5411      1126   
1296674     1296674         1    4.30  59871  45.8433 -113.8748       218   

          unix_time  merch_lat  merch_long  is_fraud  gender_F  gender_M  
0        1325376018  36.011293  -82.048315         0         1         0  
1        1325376044  49.159047 -118.186462         0         1         0  
2        1325376051  43.150704 -112.154481         0         0         1  
3        1325376076  47.034331 -112.561071         0         0         1  
4        1325376186  38.674999  -78.632459         0         0         1  
...             ...        ...         ...       ...       ...       ...  
1296670  1371816728  36.841266 -111.690765         0         0         1  
1296671  1371816739  38.906881  -78.246528         0         0         1  
1296672  1371816752  33.619513 -105.130529         0         0         1  
1296673  1371816816  42.788940 -103.241160         0         0         1  
1296674  1371816817  46.565983 -114.186110         0         0         1  

[1296675 rows x 13 columns]

In [103]:
model.fit(x,y)

LogisticRegression()

In [104]:
model.predict(m)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [105]:
model.score(m,n)

0.9961401355721147

In [106]:
from sklearn.neighbors import KNeighborsClassifier

In [109]:
knn = KNeighborsClassifier(n_neighbors = 200)

In [110]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=200)

In [111]:
knn.score(m,n)

0.9961401355721147